### ISSUE TITLE
Proton 8.0.2 workaround does not work

### ISSUE THREAD

**Issue by luisvalenzuelar** [ArkanosisNet/aoe2.arkanosis.net#2]
Hi there, thanks for this but it does not work for me. I get the following screen:

![image](https://github.com/ArkanosisNet/aoe2.arkanosis.net/assets/14203648/5dd337ea-6f74-4425-8fb0-c50a2142107f)

In Steam I selected the proton in compatibility in both the main settings and the game settings. Any idea how I can debug this?

I'm in Ubuntu 22.04.

Best

**Comment by luisvalenzuelar** [comment]
SUPER WEIRD. I added SKIPINTRO to the advanced startup configurations, as suggested in your website, and now it works!  Thanks!

**Comment by Arkanosis** [comment]
Hi @luisvalenzuelar !

Thanks for your question and sorry for not having answered earlier. Somehow I wasn't receiving any notification for issues opened on the repositories of my own organization… that should be fixed now.

I'm happy you were able to find a workaround, and thanks for sharing!

`SKIPINTRO` was needed a while ago because the intro video couldn't be played (I think it was a missing codec or something like that). It shouldn't be needed anymore with the latest versions of Proton, but it's possible that one would need the proper codec packages to be installed for Proton to use them… I don't know. Anyway, I don't think missing the intro is a going to be a dealbreaker for most people, as it's just a few seconds lost every time you start the game (plus, lately, the intro has been an ad for Xbox, something I personally don't want to see).

I'm closing the issue as solved. Thanks!
